# Site settings
title: The Fur Salon
description: > # this means to ignore newlines until "baseurl:"
  Assorted thoughts on World of Warcraft.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shaydwyrm.github.io" # the base hostname & protocol for your site
github_username: shaydwyrm

# Build settings
markdown: kramdown
